language: php
sudo: required
addons:
  sonarcloud:
    organization: "helhum-github"
    branches:
      - master
      - develop
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.sonar/cache

# Do not build feature branches or alpha/beta releases
branches:
  only:
    - master
    - develop
    - /^([0-9]+\.){1,2}(x|[0-9]+)$/

# Inform me about failures
notifications:
  email:
    - typo3@helhum.io

# This is executed for all stages
before_install:
  - if php -i | grep -q xdebug; then phpenv config-rm xdebug.ini; fi

install:
  - export COMPOSER_ROOT_VERSION=5.6.0
  - |
    composer require \
      typo3/cms-backend="$TYPO3_VERSION" \
      typo3/cms-core="$TYPO3_VERSION" \
      typo3/cms-extbase="$TYPO3_VERSION" \
      typo3/cms-extensionmanager="$TYPO3_VERSION" \
      typo3/cms-fluid="$TYPO3_VERSION" \
      typo3/cms-frontend="$TYPO3_VERSION" \
      typo3/cms-install="$TYPO3_VERSION" \
      typo3/cms-scheduler="$TYPO3_VERSION" \
      $PREFER_LOWEST
  - git checkout composer.json

# Test scripts
script:
  - .Build/bin/parallel-lint --exclude .Build .
  # This fails when command reference is not up to date
  - ./typo3cms commandreference:render > /dev/null 2>&1 && test -z "$(git diff --shortstat 2> /dev/null | tail -n1)";
  - git diff
  - .Build/bin/phpunit;

# Configure build stages (with build matrix above, test stage is implicitly defined)
jobs:
  fast_finish: true
  allow_failures:
    - env: TYPO3_VERSION="dev-master"
  include:
    - stage: test
      php: 7.2
      env: TYPO3_VERSION="~9.5.0"
    - stage: test
      php: 7.2
      env: TYPO3_VERSION=^8.7.10
    - stage: test
      php: 7.1
      env: TYPO3_VERSION=^8.7.10
    - stage: test
      php: 7.0
      env: TYPO3_VERSION=^8.7.10
    - stage: test
      php: 7.0
      env: TYPO3_VERSION=^8.7.10 PREFER_LOWEST="--prefer-lowest"
    - stage: test
      php: 7.2
      env: TYPO3_VERSION="dev-master"

    - stage: test
      php: 7.0
      env: Consistency checks
      install: skip
      before_script: skip
      script:
        - >
          if [ -n "$TRAVIS_TAG" ]; then
            composer set-version $TRAVIS_TAG
            test -z "$(git diff --shortstat 2> /dev/null | tail -n1)";
          fi
        - composer extension-verify-composer-json
        - composer extension-create-libs

    - stage: sonar code scanner
      if: type = push AND branch IN (master, develop)
      php: 7.2
      before_install: skip
      install: skip
      before_script:
      script:
        - git fetch --unshallow
        - export COMPOSER_ROOT_VERSION=5.6.0
        - composer install
        - .Build/bin/phpunit --whitelist Classes --coverage-clover .Build/clover.xml --log-junit .Build/junit.xml
        - >
          if [ -n "$SONAR_TOKEN" ]; then
            sonar-scanner
          fi

    - stage: ðŸš¢ to TER
      if: tag IS present
      php: 7.0
      install: skip
      before_script: skip
      script:
        - |
          if [ -n "$TYPO3_ORG_USERNAME" ] && [ -n "$TYPO3_ORG_PASSWORD" ]; then
            echo -e "Preparing upload of release ${TRAVIS_TAG} to TER\n";
            # Install ter client
            composer global require helhum/ter-client

            # Build extension files
            composer extension-release

            # Upload
            TAG_MESSAGE=`git tag -n10 -l $TRAVIS_TAG | sed 's/^[0-9.]*[ ]*//g'`
            echo "Uploading release ${TRAVIS_TAG} to TER"
            $HOME/.composer/vendor/bin/ter-client upload typo3_console . -u "$TYPO3_ORG_USERNAME" -p "$TYPO3_ORG_PASSWORD" -m "$TAG_MESSAGE"
          fi;
