language: php

php:
  - 5.5
  - 5.6
  - 7

env:
  - TYPO3_VERSION=^7.6.0
  - TYPO3_VERSION=dev-master

matrix:
  exclude:
    - php: 5.5
      env: TYPO3_VERSION=dev-master
    - php: 5.6
      env: TYPO3_VERSION=dev-master

sudo: false
cache:
  directories:
    - $HOME/.composer/cache

addons:
  apt:
    packages:
      - parallel

notifications:
  email:
    - helmut@typo3.org

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer --version
  - if [ "$GITHUB_COMPOSER_AUTH" ]; then composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH; fi

before_script:
  - composer require typo3/cms=$TYPO3_VERSION

script:
  - >
    echo;
    echo "Running unit tests";
    TYPO3_PATH_WEB=".Build/Web" .Build/bin/phpunit -c .Build/vendor/typo3/cms/typo3/sysext/core/Build/UnitTests.xml Tests/Unit/
  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;

  # Basic functional tests - all commands should exit with 0
  - ./typo3cms help && [ ! -f "typo3conf/PackageStates.php" ]
  - ./typo3cms install:setup --non-interactive --database-user-name="root" --database-host-name="localhost" --database-port="3306" --database-name="travis_test" --admin-user-name="admin" --admin-password="password" --site-name="Travis Install"
  - ./typo3cms help
  - ./typo3cms backend:lock
  - ./typo3cms backend:unlock
  - ./typo3cms cache:flush
  - ./typo3cms cache:listgroups
  - ./typo3cms cleanup:updatereferenceindex
  - ./typo3cms database:updateschema "*"
  - ./typo3cms documentation:generatexsd TYPO3\\CMS\\Fluid\\ViewHelpers > /dev/null
  - rm -f .Build/Web/typo3conf/PackageStates.php && ./typo3cms install:generatepackagestates && [ -f ".Build/Web/typo3conf/PackageStates.php" ]
  - rm .Build/Web/typo3temp/index.html && ./typo3cms install:fixfolderstructure && [ -f ".Build/Web/typo3temp/index.html" ]

after_script:
  - >
    if [ -n "$TRAVIS_TAG" ] && [ -n "$TYPO3_ORG_USERNAME" ] && [ -n "$TYPO3_ORG_PASSWORD" ]; then
      echo -e "Preparing upload of release ${TRAVIS_TAG} to TER\n"
      curl -sSL https://raw.githubusercontent.com/alrra/travis-after-all/1.4.4/lib/travis-after-all.js | node
      if [ $? -eq 0 ]; then
        # Cleanup before we upload
        git reset --hard HEAD && git clean -fx

        TAG_MESSAGE=`git tag -n10 -l $TRAVIS_TAG | sed 's/^[0-9.]*[ ]*//g'`
        echo "Uploading release ${TRAVIS_TAG} to TER"
        .Build/bin/upload . "$TYPO3_ORG_USERNAME" "$TYPO3_ORG_PASSWORD" "$TAG_MESSAGE"
      fi;
    fi;
