language: php

php:
  - 5.5
  - 5.6

env:
  global:
    - secure: "2jkWz3b8tfN5yCHKbdn02Fd0doKcDXWAQW+h0DJcGzIqBT2OBn5xWHMCRketdo7J9BYcmIVipfCNVxN7QOmJCQeXUWhO4LQPLX0zDkXKP9Tht/cOA2HNNCcIcw5WMucEmeIXWP3ahNdGoUF72TSuKr58Y8VRTfjoTdIq9LL5RIY="
  matrix:
    - TYPO3_VERSION=dev-master

sudo: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email:
    - helmut@typo3.org

before_install:
  - composer self-update
  - if [ "$GITHUB_COMPOSER_AUTH" ]; then composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH; fi

before_script:
  - composer require typo3/cms=$TYPO3_VERSION
# We currently need to get rid of the typo3/cms requirement in composer.json
  - git reset --hard HEAD
  - export TYPO3_PATH_WEB=$PWD/vendor/web

script:
  - >
    echo;
    echo "Running unit tests";
    vendor/bin/phpunit -c vendor/typo3/cms/typo3/sysext/core/Build/UnitTests.xml Tests/Unit/
  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./vendor/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
# Basic functional tests - all commands should exit with 0
  - cd $TYPO3_PATH_WEB
  - ./typo3cms help && [ ! -f "typo3conf/PackageStates.php" ]
  - ./typo3cms install:setup --non-interactive --database-user-name="root" --database-host-name="localhost" --database-port="3306" --database-name="travis_test" --admin-user-name="admin" --admin-password="password" --site-name="Travis Install"
  - ./typo3cms help
  - ./typo3cms backend:lock
  - ./typo3cms backend:unlock
  - ./typo3cms cache:flush
  - ./typo3cms cache:listgroups
  - ./typo3cms cache:warmup
  - ./typo3cms cleanup:updatereferenceindex
  - ./typo3cms database:updateschema "*"
  - ./typo3cms documentation:generatexsd TYPO3\\CMS\\Fluid\\ViewHelpers
