language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

matrix:
  exclude:
    - php: 5.3
      env: TYPO3_VERSION=dev-master
    - php: 5.4
      env: TYPO3_VERSION=dev-master

env:
  global:
    - secure: "2jkWz3b8tfN5yCHKbdn02Fd0doKcDXWAQW+h0DJcGzIqBT2OBn5xWHMCRketdo7J9BYcmIVipfCNVxN7QOmJCQeXUWhO4LQPLX0zDkXKP9Tht/cOA2HNNCcIcw5WMucEmeIXWP3ahNdGoUF72TSuKr58Y8VRTfjoTdIq9LL5RIY="
  matrix:
    - TYPO3_VERSION=dev-master
    - TYPO3_VERSION=6.2.*

sudo: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email:
    - helmut@typo3.org

before_script:
  - if [ "$GITHUB_COMPOSER_AUTH" ]; then composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH; fi
  - export REPO_URL=`git remote -v | sed 's/^origin\s*\([^ ]*\) (fetch)$/\1/gp;d'`
  - echo $TRAVIS_PULL_REQUEST
  - cd ..
  - composer create-project typo3/cms=$TYPO3_VERSION travis-build
  - cd travis-build
  - composer config repositories.console vcs "$REPO_URL"
  - echo composer require helhum/typo3-console="dev-$TRAVIS_BRANCH#$TRAVIS_COMMIT"
  - composer require helhum/typo3-console="dev-$TRAVIS_BRANCH#$TRAVIS_COMMIT"
  - cp typo3conf/ext/typo3_console/Scripts/typo3cms .
  - if [ $TRAVIS_PULL_REQUEST != "false" ]; then cd typo3conf/ext/typo3_console; git fetch origin "+refs/pull/$TRAVIS_PULL_REQUEST/merge:" && git checkout -qf FETCH_HEAD && git status && git show && cd - ;fi

script:
  - >
    echo;
    echo "Running unit tests";
    ./bin/phpunit --colors -c typo3/sysext/core/Build/UnitTests.xml typo3conf/ext/typo3_console/Tests/Unit/
  - >
    echo;
    echo "Running php lint";
    find typo3conf/ext/typo3_console/ -name \*.php | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
# Basic functional tests - all commands should exit with 0
  - ./typo3cms help && [ ! -f "typo3conf/PackageStates.php" ]
  - ./typo3cms install:setup --non-interactive --database-user-name="root" --database-host-name="localhost" --database-port="3306" --database-name="travis_test" --admin-user-name="admin" --admin-password="password" --site-name="Travis Install"
  - ./typo3cms help
  - ./typo3cms cache:flush
  - ./typo3cms cache:listgroups
  - ./typo3cms cache:warmup
  - ./typo3cms backend:lock
  - ./typo3cms backend:unlock
  - ./typo3cms cleanup:updatereferenceindex