language: php
sudo: false

branches:
  only:
    - master
    - develop
    - /^([0-9]+\.){1,2}(x|[0-9]+)$/

php:
  - 7.1
  - 7.0

env:
  - TYPO3_VERSION=^8.7
  - TYPO3_VERSION="dev-master as 8.7.7"

cache:
  directories:
    - $HOME/.composer/cache

addons:
  apt:
    packages:
      - parallel

notifications:
  email:
    - typo3@helhum.io

before_install:
  - |
    export COMPOSER_ROOT_VERSION=5.0.0
    export PATH="$PATH:./Scripts"
  - if php -i | grep -q xdebug; then phpenv config-rm xdebug.ini; fi

before_script:
  - >
    if [ -n "$TRAVIS_TAG" ]; then
      composer set-version $TRAVIS_TAG
      # If this fails, we forgot to update version numbers before tagging the release
      test -z "$(git diff --shortstat 2> /dev/null | tail -n1)";
    fi
  - composer extension-create-libs && ls -la Libraries/*.phar | grep -v ^-rwx
  - git clean -dffx
  - composer require typo3/cms="$TYPO3_VERSION"
  - git checkout composer.json

script:
  # This fails when command reference is not up to date
  - typo3console commandreference:render > /dev/null 2>&1 && test -z "$(git diff --shortstat 2> /dev/null | tail -n1)";
  - >
    echo "Running php lint…";
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;;
  - >
    echo "Running unit and functional tests…";
    .Build/bin/phpunit;
jobs:
  fast_finish: true
  allow_failures:
    - env: TYPO3_VERSION="dev-master as 8.7.7"
  include:
    - stage: publish in ter
      php: 7.1
      env: TYPO3_VERSION=
      install: skip
      before_script: skip
      script:
        - |
          if [ -n "$TRAVIS_TAG" ] && [ -n "$TYPO3_ORG_USERNAME" ] && [ -n "$TYPO3_ORG_PASSWORD" ]; then
            echo -e "Preparing upload of release ${TRAVIS_TAG} to TER\n";
            # Cleanup before we upload
            composer require --dev typo3/cms ^8.7 --update-with-dependencies
            composer require --dev helhum/ter-client dev-master
            git reset --hard HEAD && git clean -fx

            # Build extension files
            composer extension-release

            # Upload
            TAG_MESSAGE=`git tag -n10 -l $TRAVIS_TAG | sed 's/^[0-9.]*[ ]*//g'`
            echo "Uploading release ${TRAVIS_TAG} to TER"
            .Build/bin/ter-client upload typo3_console . -u "$TYPO3_ORG_USERNAME" -p "$TYPO3_ORG_PASSWORD" -m "$TAG_MESSAGE"
          fi;
