build: false
platform: x86
clone_folder: c:\t3c
services:
  - mysql

environment:
  COMPOSER_NO_INTERACTION: 1
  TYPO3_INSTALL_DB_USER: 'root'
  TYPO3_INSTALL_DB_PASSWORD: 'Password12!'
  TYPO3_INSTALL_DB_DBNAME: 'appveyor_console_test'

  matrix:
    - TYPO3_VERSION: '~10.4.0'
      PHP_VERSION: '7.3.15-Win32-VC15'

matrix:
  fast_finish: true

cache:
  - c:\php -> appveyor.yml
  - '%LOCALAPPDATA%\Composer\files'

init:
  - SET PATH=c:\php\%PHP_VERSION%;"C:\Program Files\MySQL\MySQL Server 5.7\bin\";%PATH%

install:
  - mysql --version
  - IF NOT EXIST c:\php mkdir c:\php
  - IF NOT EXIST c:\php\%PHP_VERSION% mkdir c:\php\%PHP_VERSION%
  - cd c:\php\%PHP_VERSION%
  - IF NOT EXIST php-installed.txt curl -fsS -o php-%PHP_VERSION%-x86.zip https://windows.php.net/downloads/releases/archives/php-%PHP_VERSION%-x86.zip
  - IF NOT EXIST php-installed.txt 7z x php-%PHP_VERSION%-x86.zip -y >nul
  - IF NOT EXIST php-installed.txt del /Q *.zip
  - IF NOT EXIST php-installed.txt copy /Y php.ini-development php.ini
  - IF NOT EXIST php-installed.txt echo max_execution_time=1200 >> php.ini
  - IF NOT EXIST php-installed.txt echo date.timezone="UTC" >> php.ini
  - IF NOT EXIST php-installed.txt echo extension_dir=ext >> php.ini
  - IF NOT EXIST php-installed.txt echo extension=php_curl.dll >> php.ini
  - IF NOT EXIST php-installed.txt echo extension=php_openssl.dll >> php.ini
  - IF NOT EXIST php-installed.txt echo extension=php_mbstring.dll >> php.ini
  - IF NOT EXIST php-installed.txt echo extension=php_fileinfo.dll >> php.ini
  - IF NOT EXIST php-installed.txt echo extension=php_mysqli.dll >> php.ini
  - IF NOT EXIST php-installed.txt curl -fsS -o composer.phar https://getcomposer.org/download/1.10.5/composer.phar
  - IF NOT EXIST php-installed.txt echo @php %%~dp0composer.phar %%* > composer.bat
  - IF NOT EXIST php-installed.txt type nul >> php-installed.txt

  - cd c:\t3c
  - composer require --no-update "typo3/cms-backend=%TYPO3_VERSION%" "typo3/cms-core=%TYPO3_VERSION%" "typo3/cms-extbase=%TYPO3_VERSION%" "typo3/cms-extensionmanager=%TYPO3_VERSION%" "typo3/cms-fluid=%TYPO3_VERSION%" "typo3/cms-frontend=%TYPO3_VERSION%" "typo3/cms-install=%TYPO3_VERSION%" "typo3/cms-recordlist=%TYPO3_VERSION%" --prefer-dist --no-progress --ansi
  - composer update
  - git checkout .

test_script:
  - cd c:\t3c
  - .Build\bin\phpunit
