name: Analyze

on:
    push:
        branches:
            - main
            - develop
            - /^v?([0-9]+\.){1,2}(x|[0-9]+)-?[a-z]*[1-9]*$/

defaults:
    run:
        shell: bash

jobs:
    Sonar-Cloud:
        name: 'Sonar Cloud'
        if: github.repository == 'TYPO3-Console/TYPO3-Console'
        runs-on: ubuntu-latest

        steps:
            -   name: Start database server
                run: sudo /etc/init.d/mysql start

            -   name: Checkout
                uses: actions/checkout@v3
                with:
                    fetch-depth: 0

            -   name: Composer Cache Vars
                id: composer-cache-vars
                run: |
                    echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
                    echo "timestamp=$(date +"%s")" >> $GITHUB_OUTPUT

            -   name: Cache Composer dependencies
                uses: actions/cache@v3
                with:
                    path: ${{ steps.composer-cache-vars.outputs.dir }}
                    key: ${{ runner.os }}-composer-^11.5.3-stable-8.1-${{ steps.composer-cache-vars.outputs.timestamp }}
                    restore-keys: |
                        ${{ runner.os }}-composer-^11.5.3-stable-8.1-
                        ${{ runner.os }}-composer-^11.5.3-stable-
                        ${{ runner.os }}-composer-^11.5.3-
                        ${{ runner.os }}-composer-

            -   name: Set up PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.1

            -   name: Test
                run: |
                    if [ -n "${{ secrets.SONAR_TOKEN }}" ]; then
                        export COMPOSER_ROOT_VERSION=7.1.6
                        composer update
                        vendor/bin/phpunit --whitelist Classes --coverage-clover var/clover.xml --log-junit var/junit.xml
                    fi

            -   name: Setup sonarqube
                uses: warchant/setup-sonar-scanner@v3

            -   name: Run sonarqube
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                run: |
                    if [ -n "${{ secrets.SONAR_TOKEN }}" ]; then
                        sonar-scanner -Dsonar.host.url=https://sonarcloud.io/
                    fi
